// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSi7tFD1vnOOpRUyuBcylclleVu59HueE',
    appId: '1:820909909395:web:c0dde25c5e9d0bb7273466',
    messagingSenderId: '820909909395',
    projectId: 'untitled-7e434',
    authDomain: 'untitled-7e434.firebaseapp.com',
    storageBucket: 'untitled-7e434.appspot.com',
    measurementId: 'G-0GCZGHL7L3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHCivXkNaYhZV3yFlfh2vvLOFjVMgE_1M',
    appId: '1:820909909395:android:f10bdfbf26094098273466',
    messagingSenderId: '820909909395',
    projectId: 'untitled-7e434',
    storageBucket: 'untitled-7e434.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeCbTPB5KFUHrZcArOO4RL4ilB4orypj0',
    appId: '1:820909909395:ios:73e3493b4123bc7d273466',
    messagingSenderId: '820909909395',
    projectId: 'untitled-7e434',
    storageBucket: 'untitled-7e434.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeCbTPB5KFUHrZcArOO4RL4ilB4orypj0',
    appId: '1:820909909395:ios:73e3493b4123bc7d273466',
    messagingSenderId: '820909909395',
    projectId: 'untitled-7e434',
    storageBucket: 'untitled-7e434.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSi7tFD1vnOOpRUyuBcylclleVu59HueE',
    appId: '1:820909909395:web:d6a2031b65483593273466',
    messagingSenderId: '820909909395',
    projectId: 'untitled-7e434',
    authDomain: 'untitled-7e434.firebaseapp.com',
    storageBucket: 'untitled-7e434.appspot.com',
    measurementId: 'G-YN2B2QMGLY',
  );
}
