tpl = (1,2,3,4)
print("Tuple is : ",tpl)
list = list(tpl)
list.append(5)
print("Tuple to List is With Append 5: ",list)
list.remove(1)
print("Tuple to List is With Remove 1: ",list)
tpl = tuple(list)
print("List to Tuple is: ",tpl)
